[package]
name = "trovevm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ariadne = "0.5.1"
clap = { version = "4.5.42", features = ["derive"] }
lazy_static = "1.5.0"
miette = { version = "7.6.0", features = ["derive", "fancy"] }
pest = { version = "2.8.1", features = ["miette-error"] }
pest_derive = "2.8.1"
thiserror = "2.0.12"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
globwalk = "0.9.1"
pretty_assertions = "1.4.1"
